# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yI6y3i329rysdUPIQvhAipofhYZjmHs
"""
input= open('/content/input4.txt','r')
output_file= open('/content/output4.txt','w')
N= int(input.readline())
lines=[]
for indx in range(N):
  line= input.readline().strip()
  lines.append(line)

for i in range(len(lines)):
  for j in range(0,len(lines) - i - 1):
    first_line = lines[j].split(" ")
    second_line = lines[j+1].split(" ")
    if first_line[0] > second_line[0]:
      lines[j],lines[j+1] = lines[j+1],lines[j]
    elif first_line[0] == second_line[0] and first_line[-1] < second_line[-1]:
      lines[j],lines[j+1] = lines[j+1],lines[j]
    
for k in range(len(lines)):
  print(lines[k], file=output_file)

output_file.close()