# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sV3XDb1CXZlt01JqKNmoBNCfCEXKDkuN
"""

#Task-03
input = open('/content/input3.txt', 'r')
output = open('/content/output3.txt', 'w')
N, X = map(int, input.readline().rstrip().split())
c_denominations = list(map(int, input.readline().strip().split()))

def min_coins(coins, amount):
    dp = [float('inf')] * (amount + 1)
    dp[0] = 0

    for coin in coins:
        for i in range(coin, amount + 1):
            dp[i] = min(dp[i], dp[i - coin] + 1)

    if dp[amount] != float('inf'):
      return dp[amount]
    else:
      return -1

print(min_coins(c_denominations, X), file = output)
output.close()