# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sV3XDb1CXZlt01JqKNmoBNCfCEXKDkuN
"""

#Task-02
input = open('/content/input2.txt', 'r')
output = open('/content/output2.txt', 'w')
N = int(input.readline().strip())

def count_distinct_ways(s):
    if s <= 1:
        return 1
    ways = [0] * (s + 1)
    ways[0] = 1
    ways[1] = 1

    for i in range(2, s + 1):
        ways[i] = ways[i - 1] + ways[i - 2]
    return ways[s]

print(count_distinct_ways(N), file = output)
output.close()