# -*- coding: utf-8 -*-
"""task1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yI6y3i329rysdUPIQvhAipofhYZjmHs
"""

var1 = open('/content/input1(a).txt','r')
output_file = open('/content/output1(a).txt', 'w')
test_case = int(var1.readline())

for i in range (0,test_case):
  num = int(var1.readline())
  if num % 2 == 0:
    print(f"{num} is an Even number.", file=output_file)
  else:
    print(f"{num} is an Odd number.", file=output_file)

output_file.close()