# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yI6y3i329rysdUPIQvhAipofhYZjmHs
"""

#To ensure the best-case scenario we can keep a counter variable with a value of zero.
#If any value got swapepd then the variable value will be one. 
#After completing the inner loop we will check the the value of the counter variable. 
#If it is zero that means the given array was sorted and no value got swapped then we'll break the loop. 

def bubbleSort(arr):
    for i in range(len(arr)-1):
        counter=0
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                counter=1
        if counter==0:
            break
    return arr


input=open('/content/input2.txt','r')
output_file=open('/content/output2.txt','w')
N=int(input.readline())
list1= input.readline().strip().split(" ")
list2=[]
for i  in range(N):
  list2.append(int(list1[i]))

print(bubbleSort(list2), file=output_file)
output_file.close()