# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yI6y3i329rysdUPIQvhAipofhYZjmHs
"""

input=open('/content/input3.txt','r')
output_file=open('/content/output3.txt','w')
N = int(input.readline())
ID = input.readline().strip().split(" ")
marks = input.readline().strip().split(" ")
id_mark_list = []
for i in range(N):
  id_mark_list.append([int(ID[i]),int(marks[i])])

for val1 in range(N):
  for val2 in range(0, N - val1 - 1):
    if id_mark_list[val2][1] < id_mark_list[val2+1][1]:
      id_mark_list[val2+1],id_mark_list[val2] = id_mark_list[val2],id_mark_list[val2+1]
    elif id_mark_list[val2][1] == id_mark_list[val2+1][1] and id_mark_list[val2][0] > id_mark_list[val2+1][0]:
      id_mark_list[val2+1],id_mark_list[val2] = id_mark_list[val2],id_mark_list[val2+1]

for k in range(N):
  print(f"ID: {id_mark_list[k][0]} Mark: {id_mark_list[k][1]}",file = output_file)

output_file.close()