# -*- coding: utf-8 -*-
"""task1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17yI6y3i329rysdUPIQvhAipofhYZjmHs
"""

var1 = open('/content/input1(b).txt','r')
output_file = open('/content/output1(b).txt','w')
test_case = int(var1.readline())

for i in range(test_case):
  list1= var1.readline().split(" ")
  if list1[2] == '+':
    value=int(list1[1]) + int(list1[3].strip())
  elif list1[2] == '-':
    value=int(list1[1]) - int(list1[3].strip())
  elif list1[2] == '*':
    value=int(list1[1]) * int(list1[3].strip())
  elif list1[2] == '/':
    value=int(list1[1]) / int(list1[3].strip())

  print(f"The result of {list1[1]} {list1[2]} {list1[3].strip()} is {value}", file=output_file)

output_file.close()