# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9nXmvYW9c63a-L1-efgk1klmyzNGCGe
"""

# task3
from collections import defaultdict

input = open('/content/input3.txt', 'r')
list1 = input.readline().strip().split()
vertex = int(list1[0])
edge = int(list1[1])

G = defaultdict(list)
for x in range(edge):
    arr = input.readline().strip().split(" ")
    array = []
    for ele in arr:
        array.append(int(ele))
    G[array[0]].append(array[1])
    G[array[1]].append(array[0])

color = ["White"] * (len(G) + 1)


def DFS_visit(G, u):
    color[u] = "Grey"
    print(u, end=" ")
    for v in G[u]:
        if color[v] == "White":
            DFS_visit(G, v)
    color[u] = "Balck"


for vertex in G.keys():
    if color[vertex] == "White":
        DFS_visit(G, vertex)