# -*- coding: utf-8 -*-
"""task1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9nXmvYW9c63a-L1-efgk1klmyzNGCGe
"""

# task1(b)
input = open('/content/input1(b).txt', 'r')
list1 = input.readline().strip().split()
vertex = int(list1[0])
edge = int(list1[1])

dict1 = {}
for i in range(vertex + 1):
    dict1[i] = []

for x in range(edge):
    arr = input.readline().strip().split(" ")
    array = []
    for ele in arr:
        array.append(int(ele))
    dict1[array[0]].append((array[1:]))

for key, val in dict1.items():
    print(f"{key}:{val}")