# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9nXmvYW9c63a-L1-efgk1klmyzNGCGe
"""

# task1(a)
input = open('/content/input1(a).txt', 'r')
list1 = input.readline().strip().split()
vertex = int(list1[0])
edge = int(list1[1])

matrix = []
for i in range(vertex + 1):
    matrix.append([0] * (vertex + 1))

for x in range(edge):
    arr = input.readline().strip().split(" ")
    array = []
    for ele in arr:
        array.append(int(ele))
    matrix[array[0]][array[1]] = array[2]

for ele in matrix:
    for ver in ele:
        print(ver, end=' ')
    print()