# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y9nXmvYW9c63a-L1-efgk1klmyzNGCGe
"""

# task2(undirected)
from collections import defaultdict
input = open('/content/input2.txt', 'r')
list1 = input.readline().strip().split()
vertex = int(list1[0])
edge = int(list1[1])

G = defaultdict(list)
for x in range(edge):
    arr = input.readline().strip().split(" ")
    array = []
    for ele in arr:
        array.append(int(ele))
    G[array[0]].append(array[1])
    G[array[1]].append(array[0])

source = 1
color = ["white"] * (len(G) + 1)
queue = []
queue.append(source)
while queue != []:
    u = queue.pop(0)
    print(u, end=" ")
    for v in G[u]:
        if color[v] == "white":
            color[v] = "Black"
            queue.append(v)
    color[u] = "Black"