# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JmAOcyQU6-YeKoL08Es7J3eFuk62yjX4
"""

#task-03
input = open('/content/input3.txt', 'r')
output_file = open('/content/output3.txt','w')
r = int(input.readline().strip())
arr = input.readline().strip().split(" ")
array = []
for ele in arr:
  array.append(int(ele))


def partition(array,l,r):
    pivot=array[l]
    i=l
    j=r
    while(i<j):
        while(array[i]<=pivot and i<r):
            i+=1
        while(array[j]>pivot and j>0):
            j-=1
        if (i<j):
            array[i],array[j]=array[j],array[i]

    array[l],array[j]=array[j],array[l]
    return j


def QuickSort(array, l, r):
    if l < r:
        k = partition(array, l, r)
        QuickSort(array, l, k-1)
        QuickSort(array, k + 1, r)

    return array


print(QuickSort(array, 0, r-1), file = output_file)
output_file.close()