# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0Pk7clxcRb2qRrxYpipuckZ6HCQAg-P
"""

#task-03
input = open('/content/input3.txt', 'r')
output = open('/content/output3.txt', 'w')
vertex,edge = map(int, input.readline().rstrip().split())
pr=[]
for i in range(vertex+1):
  pr.append(i)
size=[1]*(vertex+1)

def findPr(node):
  if pr[node]==node:
    return pr[node]
  else:
    pr[node]=findPr(pr[node])
    return pr[node]

def connect(x,y):
  xpr= findPr(x)
  ypr=findPr(y)

  if xpr==ypr:
    print(size[xpr], file = output)
  else:
    pr[ypr]=xpr
    size[xpr]=size[xpr]+size[ypr]
    print(size[xpr], file = output)

for x in range(edge):
    v,e = map(int, input.readline().rstrip().split())
    connect(v,e)

output.close()