# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0Pk7clxcRb2qRrxYpipuckZ6HCQAg-P
"""

#Task-02
input = open('/content/input2.txt', 'r')
output = open('/content/output2.txt', 'w')
n, m =  map(int, input.readline().rstrip().split())
tasks = []
for i in range(n):
    start_t, end_t = map(int, input.readline().rstrip().split())
    tasks.append((start_t, end_t))

tasks.sort(key=lambda x: x[0])
last_task_time=[0]*m
count=0
for t in tasks:
  start_time, end_time = t
  for person in range(m):
    if last_task_time[person]<= start_time and last_task_time[0]-end_time!=0 :
      last_task_time[person]= end_time
      count+=1
      break

print(count, file = output)
output.close()