# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N0Pk7clxcRb2qRrxYpipuckZ6HCQAg-P
"""

#task-01
input = open('/content/input1.txt', 'r')
output = open('/content/output1.txt', 'w')
N = int(input.readline().strip())
tasks = []
for i in range(N):
    start_t, end_t = map(int, input.readline().rstrip().split())
    tasks.append((start_t, end_t))

def maximum_tasks(tasks):
    tasks.sort(key=lambda x: x[1])
    completed_tasks = []
    prev_end_time = -1
    count = 0

    for task in tasks:
        start_time, end_time = task
        if start_time >= prev_end_time:
            completed_tasks.append(task)
            prev_end_time = end_time
            count += 1

    return count, completed_tasks

max_task, final_task = maximum_tasks(tasks)

print(max_task, file = output)
for ele in final_task:
    print(ele[0], ele[1], file = output)

output.close()